# エラーコード

# デフォルトのエラー
F0000:
  msg: 不明のエラーが発生しました。
  link: index.html
  linkText: トップへ

# 連続性エラー
F0001 extends F0000:
  msg: 別の画面で操作を行ったため、続行できません。<br />お手数ですが最初から操作してください。

# 遷移チェックエラー
F0002 extends F0000:
  msg: 不正な遷移が発生しました。<br />お手数ですが最初から操作してください。

# データ不正エラー
F0003 extends F0000:
  msg: 送信データが不明です。<br />お手数ですが最初から操作してください。

# 保存失敗エラー
F0004 extends F0000:
  msg: データの保存に失敗しました。<br />お手数ですが最初から操作してください。

# データ取得エラー
F0005 extends F0000:
  msg: データの取得に失敗しました。<br />お手数ですが最初から操作してください。

