# 管理画面エラーコード

# デフォルトのエラー
A0000:
  msg: 不明のエラーが発生しました。
  link: index.html
  linkText: 管理画面トップへ

# 連続性エラー
A0001 extends A0000:
  msg: 別の画面で操作を行ったため、続行できません。<br />お手数ですが最初から操作してください。

# 遷移チェックエラー
A0002 extends A0000:
  msg: 不正な遷移が発生しました。<br />お手数ですが最初から操作してください。

# データ不正エラー
A0003 extends A0000:
  msg: 送信データが不明です。<br />お手数ですが最初から操作してください。

# 保存失敗エラー
A0004 extends A0000:
  msg: データの保存に失敗しました。<br />お手数ですが最初から操作してください。

# データ取得エラー
A0005 extends A0000:
  msg: データの取得に失敗しました。<br />お手数ですが最初から操作してください。

