if(!window.console)window.console={log:Ext.emptyFn,dir:Ext.emptyFn,debug:Ext.emptyFn,info:Ext.emptyFn,warn:Ext.emptyFn,error:Ext.emptyFn,time:Ext.emptyFn,timeEnd:Ext.emptyFn,pforile:Ext.emptyFn,pfofileEnd:Ext.emptyFn,trace:Ext.emptyFn,group:Ext.emptyFn,groupEnd:Ext.emptyFn,dirxml:Ext.emptyFn};Ext.ns("PXSTUDIO","PXSTUDIO.app","PXSTUDIO.grid","PXSTUDIO.form","PXSTUDIO.tree");
PXSTUDIO.app.App=Ext.extend(Ext.util.Observable,{commonInit:function(){Ext.apply(this,{appName:"xFrameworkPX Studio Express",version:"1.0.0a",showed:false,enable:false});Ext.form.Field.prototype.msgTarget="";Ext.BLANK_IMAGE_URL=relpath+"extjs/resources/images/default/s.gif";Ext.QuickTips.init();Ext.Direct.addProvider(PXSTUDIO.app.REMOTING_API);var a=Ext.maxZindex();if(Ext.WindowMgr.zseed<a)Ext.WindowMgr.zseed=a},initApp:function(){this.keymap=new Ext.KeyMap(document,{key:Ext.EventObject.F8,fn:function(){if(PXSTUDIO_APP.enable&&
PXDEBUG_APP.showed!==true){PXSTUDIO_APP.enable=false;this.fireEvent("showcontainer",this.showed)}},scope:this});this.on("showcontainer",function(a){if(a)this.hideContainer();else{this.archiveId=Ext.Phantom.archive(Ext.id(),["PXStudio-all.css"],[{id:"ExtJS_All_CSS",href:relpath+"extjs/resources/css/ext-all.css"},{id:"ExtJS_All_CSS_THEME",href:relpath+"extjs/resources/css/xtheme-gray.css"}]);Ext.DomHelper.insertFirst(Ext.getBody(),[{id:"pxstudio-loading-mask"}]);if(!this.bootMsg)this.bootMsg=new Ext.Layer({dh:{id:"pxdebug-loading",
cn:[{cls:"loading-indicator",cn:[{tag:"object",id:"pxdebuicon",classid:"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000",codebase:"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0",width:150,height:50,style:"margin-right:8px;",align:"absmiddle",cn:[{tag:"param",name:"allowScriptAccess",value:"sameDomain"},{tag:"param",name:"allowFullScreen",value:"false"},{tag:"param",name:"movie",value:relpath+"xFrameworkPX/studio/resources/images/pxstudioicon.swf"},{tag:"param",name:"quality",
value:"high"},{tag:"param",name:"bgcolor",value:"#ffffff"},{tag:"embed",src:relpath+"xFrameworkPX/studio/resources/images/pxstudioicon.swf",quality:"high",bgcolor:"#ffffff",width:150,height:50,name:"pxdebuicon",align:"middle",allowScriptAccess:"sameDomain",allowFullScreen:"false",type:"application/x-shockwave-flash",pluginspage:"http://www.macromedia.com/go/getflashplayer"}]}]}]}});a=Ext.getBody().getViewSize();this.bootMsg.setTop((a.height-this.bootMsg.getHeight())/2);this.bootMsg.setLeft((a.width-
this.bootMsg.getWidth())/2);this.bootMsg.show();(function(){PXSTUDIO_APP.showed=true;this.viewport=new PXSTUDIO.Viewport;this.viewport.on("hidecontainer",this.hideContainer,this);Ext.fly("pxstudio-loading-mask").remove();this.bootMsg.remove();this.bootMsg=null;PXSTUDIO_APP.enable=true}).defer(1E3,this)}},this);PXSTUDIO_APP.enable=true},hideContainer:function(){Ext.Phantom.expand(this.archiveId);this.viewport.destroy();PXSTUDIO_APP.enable=true;PXSTUDIO_APP.showed=false},run:function(){this.commonInit();
this.initApp()}});Ext.onReady(function(){if(!window.relpath)window.relpath="";window.PXSTUDIO_APP=new PXSTUDIO.app.App;PXSTUDIO_APP.run()});
Ext.apply(Ext,{maxZindex:function(){var a=0;Ext.select("*").each(function(d){d=d.getStyle("z-index");if(Ext.isNumber(parseInt(d))&&a<d)a=d},this);return a},getScrollPos:function(){return{x:document.documentElement.scrollLeft>0?document.documentElement.scrollLeft:document.body.scrollLeft,y:document.documentElement.scrollTop>0?document.documentElement.scrollTop:document.body.scrollTop}}});String.prototype.endsWith=function(a){var d=this.length-a.length;return d>=0&&this.lastIndexOf(a)===d};
Ext.Phantom=function(){var a={},d=[];return{archive:function(b,f,i){b=b||Ext.id();var e=Ext.DomHelper;Ext.isArray||(f=[]);Ext.fly(b)!==null&&Ext.fly(b).remove();a[b]=[];var j=e.append(Ext.getBody(),{id:b,style:"position: absolute; top: -10000px; left: -10000px; display: none"});if(Ext.isIE6){var k=Ext.getBody().dom;Ext.select("*",true,document).each(function(c){c.dom.parentNode.id===k.id&&j.id!=c.id&&j.appendChild(c.dom)},this)}else Ext.each(document.body.childNodes,function(c){if(c)(c=Ext.get(c))&&
c.dom.id!==b&&j.appendChild(c.dom)},this);Ext.select("link",true).each(function(c){var g=c.dom,h=g.href;if(h.indexOf("?")!=1)h=h.split("?")[0];h.toLowerCase().endsWith(".css")&&Ext.each(f,function(l){if(!h.endsWith(l)){a[b].push({id:g.id,href:g.href});g.parentNode.removeChild(g)}},this)},this);Ext.each(i,function(c){Ext.util.CSS.swapStyleSheet(c.id,c.href);d.push(c)},this);return b},expand:function(b){var f=Ext.get(b);if(Ext.isIE6){i=Ext.getBody().dom;Ext.select("*",true,f.dom).each(function(e){e.dom.parentNode.id===
f.dom.id&&document.body.appendChild(e.dom)},this)}else{var i=Ext.getBody().dom;Ext.select("*",true,f.dom).each(function(e){e.dom.parentNode.id===f.dom.id&&document.body.appendChild(e.dom)},this)}Ext.each(a[b],function(e){Ext.util.CSS.swapStyleSheet(e.id,e.href)},this);Ext.each(d,function(e){Ext.util.CSS.removeStyleSheet(e.id)},this)}}}();
PXSTUDIO.Viewport=Ext.extend(Ext.Viewport,{initComponent:function(){Ext.apply(this,{id:Ext.id()});Ext.apply(this,{layout:"fit",items:[{title:PXSTUDIO_APP.appName,iconCls:"pxstudio-icon-logo",layout:"border",tools:[{id:"gear",handler:function(){},scope:this},{id:"help",handler:function(){},scope:this},{id:"close",handler:function(){this.fireEvent("hidecontainer")},scope:this}],border:false,items:[{region:"north",border:false,tbar:[{text:"\u30d5\u30a1\u30a4\u30eb",menu:[{text:"\u7d42\u4e86",iconCls:"pxstudio-icon-logo",
handler:function(){(function(){this.fireEvent("hidecontainer")}).defer(100,this)},scope:this}]},{text:"\u7de8\u96c6"},{text:"\u691c\u7d22"},{text:"\u8868\u793a"},{text:"\u30c4\u30fc\u30eb"},{text:"\u30a6\u30a3\u30f3\u30c9\u30a6"},{text:"\u30d8\u30eb\u30d7"}],bbar:[{id:this.id+"_toolbar_vscreen",iconCls:"pxstudio-navi-vscreen-add",tooltip:"\u65b0\u898f\u4eee\u60f3\u30b9\u30af\u30ea\u30fc\u30f3\u4f5c\u6210",handler:function(){Ext.getCmp(this.id+"_Navi").fireEvent("clickToolbar","vscreen")},scope:this,
disabled:true},{id:this.id+"_toolbar_folder",iconCls:"pxstudio-navi-file",tooltip:"\u65b0\u898f\u30d5\u30a9\u30eb\u30c0\u30fc\u4f5c\u6210",handler:function(){Ext.getCmp(this.id+"_Navi").fireEvent("clickToolbar","folder")},scope:this,disabled:true},{id:this.id+"_toolbar_con",iconCls:"pxstudio-navi-file-con",tooltip:"\u65b0\u898f\u30b3\u30f3\u30c8\u30ed\u30fc\u30e9\u30fc\u4f5c\u6210",handler:function(){Ext.getCmp(this.id+"_Navi").fireEvent("clickToolbar","controller")},scope:this,disabled:true},{id:this.id+
"_toolbar_html",iconCls:"pxstudio-navi-file-html",tooltip:"\u65b0\u898f\u30c6\u30f3\u30d7\u30ec\u30fc\u30c8\u4f5c\u6210",handler:function(){Ext.getCmp(this.id+"_Navi").fireEvent("clickToolbar","template")},scope:this,disabled:true}]},{id:this.id+"_Navi",margins:"5 0 0 5",region:"west",width:250,split:true,xtype:"pxstudio-navigation",listeners:{switchToolbar:{fn:this.onSwitchToolbar,scope:this}}},{region:"south",margins:"0 5 5 5",split:true,collapsible:true,height:100,title:""},{margins:"5 5 0 0",
region:"center",activeItem:0,border:false,layout:"card",items:[{id:"PXSTUDIO_EMPTY_PANEL"}]}]}]});PXSTUDIO.Viewport.superclass.initComponent.call(this)},onSwitchToolbar:function(a){Ext.each(["vscreen","folder","con","html"],function(d){var b=Ext.getCmp(this.id+"_toolbar_"+d);a[d]?b.enable():b.disable()},this)}});
