# 追加の環境設定ファイルサンプル
#
# 呼び出し方は次のメソッドで、引数はファイル名、キー名1、キー名2、、、
# env.ymlの環境設定の設定値を見て値を返す
# getEnvVal('additional_env', 'test');
#
# /configs/yml/settings/envをルートとする
#

real:
  test: 1

stage:
  test: 2

test:
  test: 3

dev:
  test: 4
